version: '3.8'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.12.48.0/22
services:
  data-collector:
    build: .
    container_name: aster_data_collector
    environment:
      - RESTART_MINUTES=2
    env_file:
      - .env
    volumes:
      - ./ASTER_data:/app/ASTER_data
      - ./params:/app/params
      - ./data_collector.py:/app/data_collector.py:ro
      - ./api_client.py:/app/api_client.py:ro
      - ./.env:/app/.env:ro
    command: >
      sh -c "while true; do \
        python data_collector.py; \
        sleep ${RESTART_MINUTES}m; \
      done"
    restart: unless-stopped

  avellaneda-params:
    build: .
    container_name: aster_avellaneda_params
    environment:
      - PARAM_REFRESH_MINUTES=10
    env_file:
      - .env
    volumes:
      - ./ASTER_data:/app/ASTER_data
      - ./params:/app/params
      - ./calculate_avellaneda_parameters.py:/app/calculate_avellaneda_parameters.py:ro
      - ./api_client.py:/app/api_client.py:ro
    command: >
      sh -c "while true; do
        python calculate_avellaneda_parameters.py $$SYMBOL --minutes $$PARAM_REFRESH_MINUTES;
        sleep $${PARAM_REFRESH_MINUTES}m;
      done"
    restart: unless-stopped

  market-maker:
    build: .
    container_name: aster_market_maker
    environment:
      - RESTART_MINUTES=2
    env_file:
      - .env
    volumes:
      - ./ASTER_data:/app/ASTER_data
      - ./params:/app/params
      - ./market_maker.py:/app/market_maker.py:ro
      - ./api_client.py:/app/api_client.py:ro
      - ./calculate_avellaneda_parameters.py:/app/calculate_avellaneda_parameters.py:ro
      - ./.env:/app/.env:ro
    command: >
      sh -c "while true; do
        python market_maker.py --symbol $$SYMBOL;
        sleep $${RESTART_MINUTES}m;
      done"
    depends_on:
      - data-collector
      - avellaneda-params
    restart: unless-stopped

  trend-finder:
    build: .
    container_name: aster_trend_finder
    environment:
      - TREND_REFRESH_MINUTES=5
      - TREND_INTERVAL=5m
    env_file:
      - .env
    volumes:
      - ./params:/app/params
      - ./find_trend.py:/app/find_trend.py:ro
    command: >
      sh -c "while true; do
        python find_trend.py --symbol $$SYMBOL --interval $$TREND_INTERVAL;
        sleep $${TREND_REFRESH_MINUTES}m;
      done"
    restart: unless-stopped