version: '3.8'
services:
  market-maker:
    build: .
    container_name: aster_market_maker
    command: python market_maker.py --symbol ASTERUSDT
    volumes:
      - ./ASTER_data:/app/ASTER_data
      - ./params:/app/params
      - ./market_maker.py:/app/market_maker.py:ro
      - ./api_client.py:/app/api_client.py:ro
      - ./calculate_avellaneda_parameters.py:/app/calculate_avellaneda_parameters.py:ro
    env_file:
      - .env
    depends_on:
      - data-collector
    restart: unless-stopped
